keywords = ["drink play",
            "get drunk",
            "get tipsy",
            "drinker",
            "drunk",
            "wine",
            "champagne",
            "alcohol",
            "alcoholism",
            "beer",
            "beers",
            "pint",
            "pints",
            "cocktail",
            "cocktails",
            "bewery",
            "liquor",
            "booze",
            "vodka",
            "tequila",
            "gin",
            "ciroc",
            "margarita",
            "margaritas",
            "ale",
            "whiskey",
            "tipsy",
            "sober"]
